name: Project Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9.5
        uses: actions/setup-python@v1
        with:
          python-version: 3.9.5
      - name: Install dependencies
        run:
          python -m pip install --upgrade pip
          pip install -r assets/requirements.txt
      - name: Test with pytest
        run: pytest -vv                                
